language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t borapocan/complex-web-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true borapocan/complex-web-app npm run test

after_success:
  - docker tag borapocan/complex-web-app borapocan/multi-client:latest
  - docker tag borapocan/complex-web-app borapocan/multi-nginx:latest
  - docker tag borapocan/complex-web-app borapocan/multi-server:latest
  - docker tag borapocan/complex-web-app borapocan/multi-worker:latest
  - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push borapocan/multi-client:latest
  - docker push borapocan/multi-nginx:latest
  - docker push borapocan/multi-server:latest
  - docker push borapocan/multi-worker:latest
