language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t borapocan/complex-web-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true borapocan/complex-web-app npm run test

after_success:
  - docker build -t borapocan/multi-client ./client
  - docker build -t borapocan/multi-nginx ./nginx
  - docker build -t borapocan/multi-server ./server
  - docker build -t borapocan/multi-worker ./worker
  - echo "$DOCKER_SECRET" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push borapocan/multi-client
  - docker push borapocan/multi-nginx
  - docker push borapocan/multi-server
  - docker push borapocan/multi-worker
